### ISSUE TITLE
Improve commit messages quality

### ISSUE THREAD

**Issue by EdNgulele** [LSambo02/ListViewDemo#2]
Hello @LSambo02 , I was looking at your project specially your contributions and I noticed that you've been writing commit messages like:

* screenshots

It's extremely hard to understand your contribution if you don't explain it properly. Hard for us and for you, because 6months from now you won't remember what you meant by "screenshots".

I recommend you follow this [commit message style guide](https://udacity.github.io/git-styleguide/). This will only make your job easier (and ours) :)

Cheers.

**Comment by thatfiredev** [comment]
[This post](https://chris.beams.io/posts/git-commit/) by Chris Beams might also be useful.

**Comment by LSambo02** [comment]
Thank You!
Reading right now!
